name: Build with Android Gradle

on:
  workflow_dispatch:
  repository_dispatch:
    types: [register-build]

env:
  ARTIFACT_NAME: android-build
  ARTIFACT_PATH: app/build/outputs/apk/debug/app-debug.apk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          retention-days: 3

  register:
    runs-on: ${{ fromJSON(github.event.client_payload.user_config.default_runs_on) }}
    name: register
    if: github.event_name == 'repository_dispatch' && github.event.action == 'register-build'
    needs: build
    steps:
      - name: Register build
        id: register-build
        uses: veracode/github-actions-integration-helper@v0.1.9
        with:
          action: registerBuild
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          token: ${{ github.event.client_payload.token }}
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          source_repository: ${{ github.event.client_payload.repository.full_name }}
          check_run_id: ${{ github.run_id }}
          check_run_name: ${{ github.workflow }}
          head_sha: ${{ github.event.client_payload.sha }}
          event_type: ${{ github.event.client_payload.event_type }}
          branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
          issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}

  veracode-sca-scan:
    runs-on: ubuntu-latest
    name: Veracode Component Analysis
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.VERACODE_AGENT_TOKEN }}
          JAVA_OPTS: -Xms2g -Xmx4g
          VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
        uses: "veracode/veracode-sca@v2.1.17"
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
          recursive: true
          allow-dirty: true
          breakBuildOnPolicyFindings: true
          debug: true
          sca_fix_enabled: false
          profile_name: ${{ github.repository }}
          # pr_number: 